# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.6"

gem "pg", "1.5.9"
gem "zeitwerk", "2.7.1"

group :development do
  gem "rubocop", "1.69.2", require: false
  gem "bundler-audit", "0.9.2", require: false
end
