// Thumbnail pipeline.
//
// The C decoder and box filter are wrapped in RAII, and artifact names are
// resolved inside a fixed root.

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <ios>
#include <random>
#include <stdexcept>
#include <string>
#include <system_error>
#include <vector>

extern "C" {
#include "ppm.h"
#include "thumbnail.h"
}

namespace slopshop::media {
namespace fs = std::filesystem;

namespace {

// Artifact names are generated by the render service and are always a hex id
// with a fixed suffix.
constexpr std::size_t kArtifactNameLength = 32 + 4;  // 32 hex characters + ".ppm"

bool IsHexDigit(char c) {
  return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
}

bool IsWellFormedArtifactName(const std::string& name) {
  if (name.size() != kArtifactNameLength) {
    return false;
  }
  if (name.compare(32, 4, ".ppm") != 0) {
    return false;
  }
  return std::all_of(name.begin(), name.begin() + 32, IsHexDigit);
}

// Owns a ppm_image_t for the duration of a scope.
class Image {
 public:
  Image() : image_{} {}

  Image(const Image&) = delete;
  Image& operator=(const Image&) = delete;
  Image(Image&&) = delete;
  Image& operator=(Image&&) = delete;

  ~Image() { ppm_image_release(&image_); }

  ppm_image_t* get() { return &image_; }
  const ppm_image_t* get() const { return &image_; }

 private:
  ppm_image_t image_;
};

void ThrowOnPpmError(ppm_status_t status, const char* stage) {
  if (status != PPM_OK) {
    throw std::runtime_error(std::string(stage) + ": " + ppm_status_message(status));
  }
}

}  // namespace

class ThumbnailPipeline {
 public:
  ThumbnailPipeline(fs::path source_root, fs::path thumbnail_root)
      : source_root_(fs::weakly_canonical(std::move(source_root))),
        thumbnail_root_(fs::weakly_canonical(std::move(thumbnail_root))) {}

  // Produces a thumbnail for one artifact and returns the path written.
  fs::path Run(const std::string& artifact_name, std::uint32_t max_edge) const {
    if (!IsWellFormedArtifactName(artifact_name)) {
      throw std::invalid_argument("artifact name is not well formed");
    }
    if (max_edge < THUMBNAIL_MIN_EDGE || max_edge > THUMBNAIL_MAX_EDGE) {
      throw std::invalid_argument("requested edge is out of range");
    }

    const fs::path input = ResolveWithin(source_root_, artifact_name);
    const fs::path output = ResolveWithin(thumbnail_root_, artifact_name);

    const std::vector<std::uint8_t> encoded = ReadBounded(input);

    Image source;
    ThrowOnPpmError(ppm_decode(encoded.data(), encoded.size(), source.get()), "decode");

    Image thumbnail;
    ThrowOnPpmError(thumbnail_generate(source.get(), max_edge, thumbnail.get()), "downscale");

    WriteAtomically(output, Encode(*thumbnail.get()));
    return output;
  }

 private:
  // Joins `name` onto `root` and confirms the result is still under `root`.
  static fs::path ResolveWithin(const fs::path& root, const std::string& name) {
    const fs::path candidate = fs::weakly_canonical(root / name);

    const auto relative = candidate.lexically_relative(root);
    if (relative.empty() || *relative.begin() == "..") {
      throw std::invalid_argument("resolved path escapes its root");
    }
    return candidate;
  }

  static std::vector<std::uint8_t> ReadBounded(const fs::path& path) {
    // The stream is opened first and the length is taken from the open stream,
    // so the bytes that are measured are the bytes that are read.
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) {
      throw std::runtime_error("cannot open artifact for reading");
    }

    const std::streamoff size = in.tellg();
    if (size < 0) {
      throw std::runtime_error("cannot determine artifact length");
    }
    if (size == 0 || static_cast<std::uintmax_t>(size) > PPM_MAX_ENCODED_BYTES) {
      throw std::runtime_error("artifact size is outside the accepted range");
    }
    in.seekg(0, std::ios::beg);

    std::vector<std::uint8_t> buffer(static_cast<std::size_t>(size));
    in.read(reinterpret_cast<char*>(buffer.data()),
            static_cast<std::streamsize>(buffer.size()));
    if (in.gcount() != static_cast<std::streamsize>(buffer.size())) {
      throw std::runtime_error("artifact was truncated while reading");
    }
    return buffer;
  }

  static std::vector<std::uint8_t> Encode(const ppm_image_t& image) {
    // The encoder is given the capacity and reports what it used.
    std::vector<std::uint8_t> buffer(image.pixel_bytes + 32);
    std::size_t written = 0;
    ThrowOnPpmError(ppm_encode(&image, buffer.data(), buffer.size(), &written), "encode");
    buffer.resize(written);
    return buffer;
  }

  // Returns 16 hex characters from the platform entropy source.
  static std::string TemporarySuffix() {
    std::random_device source;
    std::uniform_int_distribution<unsigned> nibble(0, 15);
    static constexpr char kHex[] = "0123456789abcdef";

    std::string out;
    out.reserve(16);
    for (int i = 0; i < 16; ++i) {
      out.push_back(kHex[nibble(source)]);
    }
    return out;
  }

  // Writes to a sibling temporary and renames. The temporary carries a random
  // suffix, so two concurrent renders cannot land on the same scratch path.
  static void WriteAtomically(const fs::path& target,
                              const std::vector<std::uint8_t>& bytes) {
    fs::path temporary = target;
    temporary += "." + TemporarySuffix() + ".partial";

    {
      std::ofstream out(temporary, std::ios::binary | std::ios::trunc);
      if (!out) {
        throw std::runtime_error("cannot open thumbnail for writing");
      }
      out.write(reinterpret_cast<const char*>(bytes.data()),
                static_cast<std::streamsize>(bytes.size()));
      out.flush();
      if (!out) {
        throw std::runtime_error("failed while writing thumbnail");
      }
    }

    std::error_code ec;
    fs::rename(temporary, target, ec);
    if (ec) {
      fs::remove(temporary, ec);
      throw std::runtime_error("could not publish thumbnail");
    }
  }

  fs::path source_root_;
  fs::path thumbnail_root_;
};

}  // namespace slopshop::media
